GO
SELECT * FROM Street
WHERE Code IS NULL
GO

ALTER TABLE Street
--ALTER COLUMN Code VARCHAR(17) NOT NULL
ADD CONSTRAINT PK_Street_Code PRIMARY KEY (Code)
GO

CREATE TABLE dbo.Users(
Id INT IDENTITY(1,1) PRIMARY KEY,
LastName NVARCHAR(100),
FirstName NVARCHAR(100),
MiddleName NVARCHAR(100),
TerritoryCode VARCHAR(13) NOT NULL REFERENCES dbo.Territory(Code),
StreetCode VARCHAR(17) NOT NULL REFERENCES dbo.Street(Code),
Building INT,
Flat INT,
)
GO
